name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches:
    - '*'

jobs:
  install-lint-test-type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install yarn dependencies
        run: |
          cd template
          yarn install
          yarn add -D typescript @types/jest @types/react @types/react-native @types/react-test-renderer @types/fbemitter @types/react-redux
      - name: Run linters
        run: |
          cd template
          cp _prettierrc.js .prettierrc.js
          cp _eslintrc.js .eslintrc.js
          yarn lint
      - name: Run tests
        run: |
          cd template
          cp src/Config/index.example.js src/Config/index.js
          yarn test
      - name: Run type check
        run: |
          cd template
          cp plugins/typescript/template/tsconfig.dev.json plugins/typescript/template/tsconfig.json
          yarn type-check
